version: "3"
services:

  pgdb-ordermanagement:
    container_name: pgdb-ordermanagement
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust